# Generated by Django 3.2.6 on 2022-11-18 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_moviecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='Movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='commentcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.moviecomment'),
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
