# Generated by Django 3.2.6 on 2022-11-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemovielist',
            name='movies',
            field=models.ManyToManyField(null=True, related_name='user_like_movie_list', to='movies.Movie'),
        ),
    ]
