# Generated by Django 3.2.6 on 2022-11-18 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_moviecomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='Movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='movies.movie'),
        ),
    ]
