# Generated by Django 3.2.6 on 2022-11-18 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_moviecomment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
